# DATABASE_PASSWORD in env should probably not be blank
services:
  app:
    image: node:16
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
      DATABASE_HOST: firstreact-database-1
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./:/usr/src/app
    command: sh -c "node ./controller/Controller"

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: firstreact
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database:/data/db

  proxy:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      PROXY_SERVER_NAME: localhost
      PROXY_SERVER_PORT: 3000
      APP_SERVER_NAME: firstreact-app-1
      APP_SERVER_PORT: 3001
    ports:
      - 3000:3000

volumes:
  database:
