# DATABASE_PASSWORD environment variable is optional
# MONGO_INITDB_ROOT_PASSWORD only creates the password for a new db
# can't change for existing db
x-database-password: &database-password
      DATABASE_PASSWORD: ${DATABASE_PASSWORD-password} #for app
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD-password} #for mongo

services:
  app:
    image: node:16
    working_dir: /usr/src/app
    environment:
      <<: *database-password
      NODE_ENV: production
      DATABASE_HOST: firstreact-database-1
    volumes:
      - ./:/usr/src/app
    command: sh -c "node ./controller/Controller"

  database:
    image: mongo
    environment:
      <<: *database-password
      MONGO_INITDB_ROOT_USERNAME: firstreact
    volumes:
      - database:/data/db

  proxy:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      PROXY_SERVER_NAME: localhost
      PROXY_SERVER_PORT: 3000
      APP_SERVER_NAME: firstreact-app-1
      APP_SERVER_PORT: 3001
    ports:
      - 3000:3000

volumes:
  database:
